# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'careprovider' do
  react_native_path = "../node_modules/react-native"
  pod "yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod 'React', :path => react_native_path

  pod 'Stripe', '~> 14.0.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for careprovider
  pod 'TwilioVoice', '~> 2.0.0'

  # target 'careprovider-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'


  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'

  target 'careproviderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'careprovider-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for careprovider-tvOS

  target 'careprovider-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
    end
end
